version: '3.8'
services:
  bitcoin-core:
    image: ruimarinho/bitcoin-core:23
    container_name: bitcoind.23.0
    command:
      -printtoconsole
      -conf=/home/bitcoin/conf/bitcoin.conf
    ports:
      - 8332:8332
      - 8333:8333
      - 28332:28332
    volumes:
      - ./data:/home/bitcoin/.bitcoin
      - ./conf:/home/bitcoin/conf

